public class practice1 {
		public void abbreviatedmethod(string maxWidth){
       // public static string methodprac(string maxWidth){
            system.debug(maxWidth);
     //  String s = 'Hello Maximillian';
        String s2 = maxWidth.abbreviate(9,6);
             system.debug(s2);
   System.assertEquals('...miu...', s2);
 //System.assertEquals(8, s2.length());
    //  return s2;
           
    }
}